### ISSUE TITLE
trajectory_optimization needed?

### ISSUE THREAD

**Issue by arlk** [mikeroberts3000/flashlight#2]
You don't seem to use any of the files from `code/lib/flashlight/trajectory_optimization`, just curious as to why it is there?

Thanks!

**Comment by mikeroberts3000** [comment]
@arunlakshmanan You are correct that I never use the `trajectory_optimization` submodule in the current examples.

That being said, the functionality in that module is useful. In fact, I use that exact code in my most recent paper, Generating Dynamically Feasible Trajectories for Quadrotor Cameras. But until I have a chance to create some examples demonstrating how to use this functionality, it is not officially supported.

For the initial release of Flashlight, I decided to create examples with more detailed documentation that cover less of the functionality in Flashlight, rather than creating examples with less detailed documentation that cover more functionality. So, there is a bunch of useful code in Flashlight that isn't currently covered by any of the examples.

Feel free to ping me if you really want to use that part of Flashlight and it's blocking you not to have good examples, etc. :)
