### ISSUE TITLE
failed to import module _transformations

### ISSUE THREAD

**Issue by arlk** [mikeroberts3000/flashlight#3]
When running any file that imports `transformations.py`. I get a user warning which says that it failed to run [line 1902](https://github.com/mikeroberts3000/flashlight/blob/master/code/lib/flashlight/transformations.py#L1902):

``` bash
/home/arun/git_projs/flashlight/code/lib/flashlight/transformations.py:1888: UserWarning: failed to import module _transformations
  warnings.warn("failed to import module %s" % name)
```

**Comment by mikeroberts3000** [comment]
@arunlakshmanan Thanks for raising this issue. I get that warning too. It's safe to ignore.

This warning occurs because `flashlight/transformations.py` is actually a third party file I downloaded from somewhere, it issues this warning, and I haven't bothered to disable it. As far as I know, the module it is trying (and failing) to load is a fast C version of some of the functions in `flashlight/transformations.py`. If it can't load the fast C version, it falls back to the Python version, which is plenty fast enough for my typical use cases.

It would be better to temporarily disable warnings when importing transformations.py, or better yet, to get ahold of the fast C version. In the meantime, this behavior is somewhat documented, because that warning is visible in the examples, and the examples work correctly. But I'll leave this issue open as a reminder to fix this in a cleaner way in the next release.

**Comment by mikeroberts3000** [comment]
I've decided to close this issue because the relevant workarounds are documented here, and it will be a while before I get a chance to further improve the documentation.
